In [ ]:
# 기출문제 7회_제 3유형

# 문제 3-1
#  survived를 종속변수(Y), sex,sibsp,fare 변수를 독립변수(X)로 분석했을 때
#  아래 질문에 답하시오.
#  (단, 총 891개의 데이터에서 초기 500개 데이터로 학습, 391개 데이터로 평가 하시오)
#  (단, 모든 답은 반올림하여 소수점 둘째자리까지 구하시오)

# 1. 초기 500개 데이터로 분석시 sibsp 변수의 odds ratio는?
# 2. 초기 500개 데이터로 분석시 residual deviance는?
# 3. 나머지 391개 데이터 적용시 오분류율은?

In [1]:
######## 데이터 생성(수정금지) ########
# 데이터 불러오기
import pandas as pd

import numpy as np
# Seaborn의 내장 타이타닉 데이터셋을 불러옵니다.
import seaborn as sns
df = sns.load_dataset('titanic')
df = df[ ['survived','sex','sibsp','fare'] ] 
# sex:성별, sibsp:탑승한 부모 및 자녀 수, fare:요금
# 성별을 map 함수를 활용해서 각각 1과 0에 할당한다.(여성을 1, 남성을 0)
# (실제 시험의 지시 조건에 따를 것)
df['sex'] = df['sex'].map({'female': 1,
                           'male': 0 })
 #######################################

In [2]:
df.head()

   survived  sex  sibsp     fare
0         0    0      1   7.2500
1         1    1      1  71.2833
2         1    1      0   7.9250
3         1    1      1  53.1000
4         0    0      0   8.0500

In [3]:
train = df.iloc[ :500, : ]
test = df.iloc[500: , ]

x_train = train.drop(columns='survived')
y_train = train['survived']
x_test = test.drop(columns='survived')
y_test = test['survived']

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(500, 3) (500,)
(391, 3) (391,)

In [4]:
import statsmodels.api as sm

x_train = sm.add_constant(x_train)
model = sm.Logit(y_train, x_train).fit()
summary = model.summary()
print(summary)

Optimization terminated successfully.
         Current function value: 0.477074
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               survived   No. Observations:                  500
Model:                          Logit   Df Residuals:                      496
Method:                           MLE   Df Model:                            3
Date:                Fri, 15 Nov 2024   Pseudo R-squ.:                  0.2847
Time:                        19:13:49   Log-Likelihood:                -238.54
converged:                       True   LL-Null:                       -333.46
Covariance Type:            nonrobust   LLR p-value:                 6.573e-41
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.6815      0.174     -9.690      0.000      -2.022      -1.341
sex            2.7284      0.239     11.423      0.000       2.260       3.197
sibsp         -0.3799      0.126     -3.004      0.003      -0.628      -0.132
fare           0.0094      0.003      3.236      0.001       0.004       0.015
==============================================================================

In [6]:
x_test = sm.add_constant(x_test)
pred = model.predict(x_test)

In [7]:
# y_test
# pred

pred = np.where(pred > 0.5, 1,0)

In [16]:
# 1. 초기 500개 데이터로 분석시 sibsp 변수의 odds ratio는?

model.params
sibsp = model.params[2]
# print(sibsp)
odds_ratio = np.exp(sibsp)
print(round(odds_ratio,2))

0.68

In [ ]:
# 2. 초기 500개 데이터로 분석시 residual deviance는?
ce = -238.54 * -1  # cross_entropy = (-)Log-Likelihood  
rd = ce * 2   # residual_deviance = 2 * cross_entropy  
print(rd)

In [ ]:
# 3. 나머지 391개 데이터 적용시 오분류율은?
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

acc = accuracy_score(y_test,pred)
matrix = confusion_matrix(y_test,pred)
report = classification_report(y_test,pred)


print(acc, matrix, report)

#  오분류율 =>  1 - 정확도
print(round(1-acc, 2))

0.782608695652174 [[210  32]
 [ 53  96]]               precision    recall  f1-score   support

           0       0.80      0.87      0.83       242
           1       0.75      0.64      0.69       149

    accuracy                           0.78       391
   macro avg       0.77      0.76      0.76       391
weighted avg       0.78      0.78      0.78       391

0.22

In [21]:
# 문제 3-2
# 다음은 당뇨병 환자의 질병 진행정도 데이터셋이다.
# target을 종속변수(Y), 나머지를 독립변수(X)로 분석했을 때 아래 질문에 답하시오.
# (단, 모든 답은 반올림하여 소수점 둘째자리까지 구하시오)
# 1. target 변수와 가장 큰 상관관계를 갖는 변수의 상관계수를 구하시오.
# 2. 다중선형회귀 모델링 후 결정계수(R2 score)를 구하시오.
# 3. 문제 2에서 구한 회귀모델에서 p-value가 가장 큰 변수의 p-value값을 구하시오.

In [22]:
###############  실기환경 복사 영역  ###############
# 데이터 불러오기
import pandas as pd
import numpy as np
# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.datasets import load_diabetes
# diabetes 데이터셋 로드
diabetes = load_diabetes()
x = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
y = pd.DataFrame(diabetes.target)
y.columns = ['target'] 
df = pd.concat([x,y], axis=1)
###############  실기환경 복사 영역  ###############

In [23]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
# (단, 모든 답은 반올림하여 소수점 둘째자리까지 구하시오)
# 1. target 변수와 가장 큰 상관관계를 갖는 변수의 상관계수를 구하시오.
corr = df.corr()
corr

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
age,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731,0.187889
sex,0.173737,1.000000,0.088161,0.241010,0.035277,0.142637,-0.379090,0.332115,0.149916,0.208133,0.043062
bmi,0.185085,0.088161,1.000000,0.395411,0.249777,0.261170,-0.366811,0.413807,0.446157,0.388680,0.586450
bp,0.335428,0.241010,0.395411,1.000000,0.242464,0.185548,-0.178762,0.257650,0.393480,0.390430,0.441482
s1,0.260061,0.035277,0.249777,0.242464,1.000000,0.896663,0.051519,0.542207,0.515503,0.325717,0.212022
s2,0.219243,0.142637,0.261170,0.185548,0.896663,1.000000,-0.196455,0.659817,0.318357,0.290600,0.174054
s3,-0.075181,-0.379090,-0.366811,-0.178762,0.051519,-0.196455,1.000000,-0.738493,-0.398577,-0.273697,-0.394789
s4,0.203841,0.332115,0.413807,0.257650,0.542207,0.659817,-0.738493,1.000000,0.617859,0.417212,0.430453
s5,0.270774,0.149916,0.446157,0.393480,0.515503,0.318357,-0.398577,0.617859,1.000000,0.464669,0.565883
s6,0.301731,0.208133,0.388680,0.390430,0.325717,0.290600,-0.273697,0.417212,0.464669,1.000000,0.382483
target,0.187889,0.043062,0.586450,0.441482,0.212022,0.174054,-0.394789,0.430453,0.565883,0.382483,1.000000

In [32]:
corr1 = abs(corr['target'].sort_values(ascending=False))[1]  # bmi 변수가 상관관계가 가장 큼.
print(round(corr1, 2))

0.59

In [36]:
# 2. 다중선형회귀 모델링 후 결정계수(R2 score)를 구하시오.
x = df.drop(columns='target')
y = df['target']

import statsmodels.api as sm

x= sm.add_constant(x)
model = sm.OLS(y,x).fit()
summary = model.summary()
print(summary)

r2_score = 0.518
print(round(r2_score, 2))

                            OLS Regression Results
==============================================================================
Dep. Variable:                 target   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Fri, 15 Nov 2024   Prob (F-statistic):           3.83e-62
Time:                        21:21:33   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        152.1335      2.576     59.061      0.000     147.071     157.196
age          -10.0099     59.749     -0.168      0.867    -127.446     107.426
sex         -239.8156     61.222     -3.917      0.000    -360.147    -119.484
bmi          519.8459     66.533      7.813      0.000     389.076     650.616
bp           324.3846     65.422      4.958      0.000     195.799     452.970
s1          -792.1756    416.680     -1.901      0.058   -1611.153      26.802
s2           476.7390    339.030      1.406      0.160    -189.620    1143.098
s3           101.0433    212.531      0.475      0.635    -316.684     518.770
s4           177.0632    161.476      1.097      0.273    -140.315     494.441
s5           751.2737    171.900      4.370      0.000     413.407    1089.140
s6            67.6267     65.984      1.025      0.306     -62.064     197.318
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
0.52

In [38]:
# 3. 문제 2에서 구한 회귀모델에서 p-value가 가장 큰 변수의 p-value값을 구하시오.

p_value = 0.867
print(round(p_value, 2))

0.87